version: '3.7'
services:
  python3:
    image: "ueno_experiment"
    container_name: "fm"
    init: true
    user: "${USER_ID}:${GROUP_ID}"
    restart: always
    build: .
    working_dir: "/home/${USER_NAME}/fm/"
    tty: true
    volumes:
      - ./:/home/${USER_NAME}/fm/
    ports:
      - "8888:8888"
    build:
      context: .
      args:
        - USER_ID=${USER_ID}
        - USER_NAME=${USER_NAME}
    command: jupyter lab --ip=0.0.0.0 --no-browser

    # If you exec jupyter as root, you need --allow-root.
    # But I mapped UID as non root, so I don't need --allow-root.
    # command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
