version: '3'
services:
  python3:
    container_name: 'fm'
    user: "1000:1000"
    restart: always
    build: .
    working_dir: '/home/user/fm/'
    tty: true
    volumes:
      - ./:/home/user/fm/
